# Generated by Django 4.1.5 on 2023-03-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='foreign_agency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='women',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
