# Generated by Django 4.1.5 on 2023-01-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
